// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tazke.Api.Data;

#nullable disable

namespace Tazke.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tazke.Api.Models.Atividade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicial")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TarefaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("Tazke.Api.Models.Honorario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Honorarios");
                });

            modelBuilder.Entity("Tazke.Api.Models.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAtividades")
                        .HasColumnType("int");

                    b.Property<int>("MaxProjetos")
                        .HasColumnType("int");

                    b.Property<int>("MaxTarefas")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxAtividades = 2,
                            MaxProjetos = 2,
                            MaxTarefas = 2,
                            Nome = "Gratuito"
                        });
                });

            modelBuilder.Entity("Tazke.Api.Models.Projeto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Arquivado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroTarefa")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Tempo")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Tazke.Api.Models.ProjetoUsuario", b =>
                {
                    b.Property<long>("ProjetoId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissaoId")
                        .HasColumnType("bigint");

                    b.HasKey("ProjetoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProjetoUsuarios");
                });

            modelBuilder.Entity("Tazke.Api.Models.Tarefa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<long>("HonorarioId")
                        .HasColumnType("bigint");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProjetoId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tempo")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HonorarioId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("Tazke.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tazke.Api.Models.Atividade", b =>
                {
                    b.HasOne("Tazke.Api.Models.Tarefa", "Tarefa")
                        .WithMany("Atividades")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("Tazke.Api.Models.Honorario", b =>
                {
                    b.HasOne("Tazke.Api.Models.Usuario", "Usuario")
                        .WithMany("Honorarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tazke.Api.Models.ProjetoUsuario", b =>
                {
                    b.HasOne("Tazke.Api.Models.Projeto", "Projeto")
                        .WithMany("ProjetoUsuarios")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tazke.Api.Models.Usuario", "Usuario")
                        .WithMany("ProjetoUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tazke.Api.Models.Tarefa", b =>
                {
                    b.HasOne("Tazke.Api.Models.Honorario", "Honorario")
                        .WithMany("Tarefas")
                        .HasForeignKey("HonorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tazke.Api.Models.Projeto", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Honorario");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("Tazke.Api.Models.Usuario", b =>
                {
                    b.HasOne("Tazke.Api.Models.Plano", "Plano")
                        .WithMany("Usuarios")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Tazke.Api.Models.Honorario", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Tazke.Api.Models.Plano", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Tazke.Api.Models.Projeto", b =>
                {
                    b.Navigation("ProjetoUsuarios");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("Tazke.Api.Models.Tarefa", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("Tazke.Api.Models.Usuario", b =>
                {
                    b.Navigation("Honorarios");

                    b.Navigation("ProjetoUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
